apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: petclinic-gateway
spec:
  gatewayClassName: nginx
  infrastructure:
    parametersRef:
      group: gateway.nginx.org
      kind: NginxProxy
      name: petclinic-nginx-proxy
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "petclinic.local"